import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f8',
        'surface-container': '#eeedf3',
        'surface-container-high': '#e9e7ed',
        'surface-container-highest': '#e3e2e7',
        'surface-grouped': '#FFFFFF',
        'surface-background': '#F2F2F7',
        'surface-variant': '#e3e2e7',
        'surface': '#faf9fe',
        'on-surface': '#1a1b1f',
        'on-surface-variant': '#414755',
        'outline': '#717786',
        'outline-variant': '#c1c6d7',
        'primary': '#0058bc',
        'primary-container': '#0070eb',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#fefcff',
        'secondary': '#006e28',
        'secondary-container': '#6ffb85',
        'secondary-fixed': '#72fe88',
        'tertiary': '#894d00',
        'tertiary-container': '#ac6300',
        'tertiary-fixed': '#ffdcbf',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'charcoal-text': '#1C1C1E',
        'ios-blue': '#007AFF',
        'ios-green': '#34C759',
        'ios-orange': '#FF9500',
        'ios-red': '#FF3B30',
        'ios-gray': '#8E8E93',
        'inverse-surface': '#2f3034',
        'inverse-on-surface': '#f1f0f5',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-gap': '8px',
        'section-gap': '24px',
        'touch-target-min': '44px',
        'safe-area-inset': 'env(safe-area-inset-bottom)',
        'margin-main': '16px',
        'gutter-card': '12px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display': ['34px', { lineHeight: '41px', letterSpacing: '-0.4px', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '34px', letterSpacing: '-0.4px', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.4px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '30px', letterSpacing: '-0.4px', fontWeight: '700' }],
        'headline-md-mobile': ['20px', { lineHeight: '26px', letterSpacing: '-0.4px', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '22px', letterSpacing: '-0.4px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '20px', letterSpacing: '-0.2px', fontWeight: '400' }],
        'label-lg': ['13px', { lineHeight: '18px', letterSpacing: '0px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0px', fontWeight: '400' }],
        'numeric-data': ['20px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config
